from fastapi import FastAPI, BackgroundTasks
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
import pandas as pd
import joblib
from contextlib import asynccontextmanager
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

ml_model = {} #{"model":"credit_risk_model.pkl"}



@asynccontextmanager
async def lifespan(app: FastAPI):
    import os
    ml_model['model'] = joblib.load('credit_risk_model.pkl')
    ml_model['threshold'] = joblib.load('best_threshold.pkl')

    explainer_path = 'models/shap_explainer.pkl'
    if os.path.exists(explainer_path):
        try:
            ml_model['explainer_payload'] = joblib.load(explainer_path)
        except Exception:
            ml_model['explainer_payload'] = None
    else:
        ml_model['explainer_payload'] = None

    yield

    ml_model.clear()

app = FastAPI(
    title="Credit Risk Assessment & Explainability Service",
    description="Production ML service with XGBoost calibration and real-time SHAP explanations",
    version="1.0.0",
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


#The only columns that user will see and provide inputs.
class LoanApplication(BaseModel): #Pydantic Model (Validation)
    person_age: int
    person_income: float
    person_home_ownership: str
    person_emp_length: float
    loan_intent: str
    loan_grade: str
    loan_amnt: float
    loan_int_rate: float
    loan_percent_income: float
    cb_person_default_on_file: str
    cb_person_cred_hist_length: int



@app.post('/predict')
def predict(data: LoanApplication, background_tasks: BackgroundTasks):
    input_data = data.model_dump() if hasattr(data, "model_dump") else data.dict()
    input_df = pd.DataFrame([input_data])

    probability = float(ml_model['model'].predict_proba(input_df)[:, 1][0])

    prediction = int(probability >= ml_model["threshold"])

    # Asynchronously log inference event for drift analysis
    try:
        from src.inference_logger import log_inference
        background_tasks.add_task(log_inference, input_data, probability, prediction)
    except Exception:
        pass

    return {
        "default_probability": probability,
        "default_prediction": prediction,
        "threshold": float(ml_model["threshold"]),
        "Result": "High Risk" if prediction == 1 else "Low Risk"
    }


@app.get('/monitoring/report', response_class=HTMLResponse)
def get_monitoring_report():
    """
    Renders the Evidently AI interactive drift and data quality report.
    """
    import os
    report_path = "static/drift_report.html"
    if not os.path.exists(report_path):
        try:
            from src.monitoring import run_drift_analysis
            run_drift_analysis(output_html=report_path)
        except Exception as e:
            return HTMLResponse(content=f"<h3>Drift report not yet generated: {e}</h3>", status_code=503)

    with open(report_path, "r", encoding="utf-8") as f:
        html_content = f.read()
    return HTMLResponse(content=html_content)


@app.post('/monitoring/run')
def trigger_monitoring_run(background_tasks: BackgroundTasks):
    """
    Triggers an on-demand Evidently AI drift analysis in the background.
    """
    def task():
        try:
            from src.monitoring import run_drift_analysis
            run_drift_analysis()
        except Exception as e:
            print(f"Drift task error: {e}")

    background_tasks.add_task(task)
    return {"status": "accepted", "message": "Evidently AI drift analysis initiated in background."}


@app.get('/monitoring/status')
def get_monitoring_status():
    """
    Returns latest drift metrics summary JSON.
    """
    import os, json
    summary_path = "models/drift_summary.json"
    if os.path.exists(summary_path):
        with open(summary_path, "r") as f:
            return json.load(f)
    return {"status": "no_report_available", "message": "Run POST /monitoring/run or view /monitoring/report first."}


@app.post('/explain')
def explain(data: LoanApplication):
    """
    Computes local feature importance using SHAP for the given applicant.
    """
    import os
    if not ml_model.get('explainer_payload'):
        explainer_path = 'models/shap_explainer.pkl'
        if os.path.exists(explainer_path):
            try:
                ml_model['explainer_payload'] = joblib.load(explainer_path)
            except Exception as e:
                return {"status": "error", "message": f"Failed to load explainer: {e}"}
        else:
            return {
                "status": "explainer_unavailable",
                "message": "SHAP explainer model is being generated by the training pipeline."
            }

    try:
        from src.explain import explain_instance
        input_data = data.model_dump() if hasattr(data, "model_dump") else data.dict()
        input_df = pd.DataFrame([input_data])

        fitted_preprocessor = ml_model['model'].calibrated_classifiers_[0].estimator.named_steps["preprocessor"]
        explanation = explain_instance(ml_model['explainer_payload'], fitted_preprocessor, input_df)
        return {"status": "success", **explanation}
    except Exception as e:
        return {"status": "error", "message": str(e)}

app.mount("/", StaticFiles(directory="static", html=True), name="static")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
